site_name: Deployment Automation Framework For You
theme:
  name: material
  #custom_dir: overrides
  logo: images/ducks.png
  favicon: images/ducks.png
  icon:
    admonition:
      <type>: material/alert
  palette:
    scheme: default
    primary: black
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - toc.follow
    - navigation.sections
  #  - navigation.expand
    - navigation.tracking
nav:
  - Home: index.md
  - Overview:
    - Overview/index.md
    - Tools Installed: Overview/Tools-Installed.md
  - Deploying OCP:
    - Deploying-OCP/index.md
    - Pre-Req: Deploying-OCP/Pre-Req.md
    - Core Steps: Deploying-OCP/Core-steps.md
    - IBM Gym: Deploying-OCP/IBM-gym.md
    - GCP: Deploying-OCP/GCP.md
    - KVM: Deploying-OCP/kvm.md
    - Azure: Deploying-OCP/Azure.md
    - AWS: Deploying-OCP/AWS.md
    - VSphere: Deploying-OCP/VSphere.md
    - ROKS: Deploying-OCP/ROKS.md
    - TechZone: Deploying-OCP/TechZone.md
    - Restricted Network: Deploying-OCP/Air-Gap.md
#    - Pre-built Clusters: Deploying-OCP/Pre-Built-Cluster.md
  - Cloud Paks:
    - Cloud-Paks/index.md
    - Business Automation: Cloud-Paks/Business-Automation.md
    - Data: Cloud-Paks/Data.md
    - Integration: Cloud-Paks/Integration.md
    - Watson AIOPS: Cloud-Paks/Watson-AIOPS.md
    - WebSphere Automation: Cloud-Paks/WebSphere-Automation.md
  - Supporting Software:
    - Supporting-Software/index.md
    - DB2: Supporting-Software/DB2.md
    - IBM LDAP: Supporting-Software/IBM-LDAP.md
    - Create Your Own Bastion: Supporting-Software/Create-Your-Own-Bastion.md
    - Turbo: Supporting-Software/Turbo.md
  - Tips & Tricks:
    - Common Issues: Tips-&-Tricks/Common-Issues.md
    - Environment File: Tips-&-Tricks/Environment-File.md
    - Edit Files: Tips-&-Tricks/Edit-Files.md
  - Request Forms:
    - Request-Forms/index.md
    #- Demo Request: Request-Forms/Demo-Request.md
    #- Feature Request: Request-Forms/Feature-Requests.md
    #- Get Involved: Request-Forms/Get-Involved.md
    #- POC Request Form: Request-Forms/POC-Request-Form.md
    #- Training: Request-Forms/Training.md
    #- L200 Adv Training: Request-Forms/L200-Adv-Training.md
  - Meet the Team:
    - Meet-the-Team/index.md
    #- Meet The teamm 2: Meet-the-Team/Meat-the-Team.md
    #- Workstreams: Meet-the-Team/Workstreams.md
  - More:
    - Glossary: More/Glossary.md
    - FAQ: More/FAQ/FAQ.md
    - Deployment Estimates: More/FAQ/Deployment-Estimates.md
    - IBM Entitlement Keys: More/FAQ/IBM-Entitlement Keys.md
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - meta
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.keys
  #- pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
extra_css:
    - css/extra.css
    - css/code.css
